dist: bionic
language: node_js
node_js:
- 16
script:
  - npm test
deploy:
  app: zgz
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_API_KEY
  on:
    all_branches: true
before_install:
  - cd BackEnd
  - openssl aes-256-cbc -K $encrypted_c533bc14502a_key -iv $encrypted_c533bc14502a_iv -in Secret.js.enc -out Secret.js -d
  - gem install faraday -v 1.8.0
install:
  - npm install
